export const API = {
  USER: process.env.VUE_APP_API_DOMAIN + '/api/user',
  REGISTER: process.env.VUE_APP_API_DOMAIN + '/api/register',
  LOGIN: process.env.VUE_APP_API_DOMAIN + '/api/login',
  LOGOUT: process.env.VUE_APP_API_DOMAIN + '/api/logout',
  RESET_PASSWORD: process.env.VUE_APP_API_DOMAIN + '/api/reset-password',
  REGENERATE_PASSWORD: process.env.VUE_APP_API_DOMAIN + '/api/regenerate-password',
  CHANGE_REGISTRATION: process.env.VUE_APP_API_DOMAIN + '/api/change-registration',
  DISTANCE: process.env.VUE_APP_API_DOMAIN + '/api/distance',
  SETTING: process.env.VUE_APP_API_DOMAIN + '/api/setting',
  GEO_DB_CITIES: process.env.VUE_APP_API_DOMAIN + '/api/external/geo-db-cities',
  WIKI_CITY: process.env.VUE_APP_API_DOMAIN + '/api/external/wiki-city',
  FACILITY: process.env.VUE_APP_API_DOMAIN + '/api/external/facility',
  HOTEL: process.env.VUE_APP_API_DOMAIN + '/api/external/hotel',
  WEATHER: process.env.VUE_APP_API_DOMAIN + '/api/external/weather',
  NEAR_BY_SEARCH: process.env.VUE_APP_API_DOMAIN + '/api/external/near-by-search',
  GOOGLE_PLACE: process.env.VUE_APP_API_DOMAIN + '/api/google-place',
}